### PR TITLE
[flight] make the enforce_schema function public

### PR DESCRIPTION
**Pull request by ccciudatu**
Expose the (slightly enhanced) `enforce_schema` function to downstream application code.

### CODE REVIEW

**Review by phillipleblanc — APPROVED** [review]
Thanks!

**Comment by ccciudatu** [comment]
FWIW, I think this functionality is generic enough to be useful in a far broader context, beyond flight and even table-providers. My guess is there are variations of this already rewritten again and again across various projects.
@alamb do you think this would be a good fit for upstream crates like `arrow-cast` or `datafusion-common`?

**Comment by alamb** [comment]
> FWIW, I think this functionality is generic enough to be useful in a far broader context, beyond flight and even table-providers. My guess is there are variations of this already rewritten again and again across various projects. @alamb do you think this would be a good fit for upstream crates like `arrow-cast` or `datafusion-common`?

I took a quick look at what `enforce_schema` does and it looks to me like it does something called "schema evolution" in other contexts

This code in DataFusion seems to do the same thing (map a batch schema to a target schema, filling in null columns / casting types when needed): 
https://docs.rs/datafusion/latest/datafusion/datasource/schema_adapter/struct.DefaultSchemaAdapterFactory.html

**Comment by alamb** [comment]
The docs were a bit lackluster so I added some more here: https://github.com/apache/datafusion/pull/13063

**Pull request merged**
