### PR TITLE
Correctly handle mysql timestamp() and datetime() types

### PR DESCRIPTION
**Pull request by Sevenannn**
This PR includes the changes to correctly handle MySQL timestamp() and datetime() types when converting to arrow types.
* MySQL timestamp(1-6) and timestamp() are all `MYSQL_TYPE_TIMESTAMP` 
* MySQL datetime(1-6) and datetime() are all `MYSQL_TYPE_DATETIME`
* Use arrow `TimestampMicrosecond` type for mapping `MYSQL_TYPE_TIMESTAMP` and `MYSQL_TYPE_DATETIME` types, to handle up to microsecond precision for timestamp & datetime types
* Simplify the logic for convert `MYSQL_TYPE_TIMESTAMP` and `MYSQL_TYPE_DATETIME` values to arrow `TimestampMicrosecond` value

### CODE REVIEW

**Review by hozan23 — COMMENTED** [review]
Thanks @Sevenannn, nice work. 

I wonder if we could add some tests here. Just to cover all ranging precision from 0-6 with the `TIMESTAMP` type.

> A DATETIME or TIMESTAMP value can include a trailing fractional seconds part in up to microseconds (6 digits) precision. In particular, any fractional part in a value inserted into a DATETIME or TIMESTAMP column is stored rather than discarded.

https://dev.mysql.com/doc/refman/8.4/en/datetime.html

**Comment by Sevenannn** [comment]
Thanks for the feedback! @hozan23 

I added tests for MySQL `TIMESTAMP` and `DATETIME` types, and they are now running as part of the PR test.

**Review by phillipleblanc — APPROVED** [review]

**Comment by hozan23** [comment]
@phillipleblanc  any reason not to merge this into the main branch?

**Comment by phillipleblanc** [comment]
It should be merged it into main. Once we (Spice AI) migrate to main from our `spiceai` branch (TBD), it will eventually be merged in. If you want to bring it in faster, I'm happy to review the PR.

**Comment by hozan23** [comment]
> It should be merged it into main. Once we (Spice AI) migrate to main from our `spiceai` branch (TBD), it will eventually be merged in. If you want to bring it in faster, I'm happy to review the PR.

Hey @phillipleblanc, here is the PR #112

**Pull request merged**
