### PR TITLE
Upgrade dafafusion to 43.0.0

### PR DESCRIPTION
**Pull request by holicc**

### CODE REVIEW

**Review by phillipleblanc — APPROVED** [review]
Thanks @holicc!

**Comment by phillipleblanc** [comment]
Looks like a couple of tests are still failing - I'll merge this once those are cleaned up.

**Comment by holicc** [comment]
@phillipleblanc It's unusual that I can't reproduce the failure of the test `test_duckdb_connection_pool_with_attached_databases` on my laptop. Is there anything I missed?

**Comment by holicc** [comment]
@phillipleblanc  This test case `test_duckdb_connection_pool_with_attached_databases` is very flaky; it may crash randomly and is not related to this PR. I don't know how to fix it.

**Comment by phillipleblanc** [comment]
> @phillipleblanc This test case `test_duckdb_connection_pool_with_attached_databases` is very flaky; it may crash randomly and is not related to this PR. I don't know how to fix it.

Yeah, I think we should remove it then.

**Comment by phillipleblanc** [comment]
@holicc I've merged this PR since the test is flaky. Thanks for working on this! If you'd like to submit a PR for removing that flaky test, I'll merge it as well.

**Pull request merged**
